CFLAGS= -Wall -coverage -fpic -lm -std=c99

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)
#To run playdom you need to entere: ./playdom <any integer number> like ./playdom 10*/
testDrawCard: testDrawCard.c dominion.o rngs.o
	gcc  -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

badTestDrawCard: badTestDrawCard.c dominion.o rngs.o
	gcc -o badTestDrawCard -g  badTestDrawCard.c dominion.o rngs.o $(CFLAGS)

testBuyCard: testDrawCard.c dominion.o rngs.o
	gcc -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

testAll: dominion.o testSuite.c
	gcc -o testSuite testSuite.c -g  dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

unittest1.o: unittest1.c
	gcc -c unittest1.c -g $(CFLAGS)

unittest2.o: unittest2.c
	gcc -c unittest2.c -g $(CFLAGS)
unittest3.o: unittest3.c
	gcc -c unittest3.c -g $(CFLAGS)
unittest4.o: unittest4.c
	gcc -c unittest4.c -g $(CFLAGS)
unittest5.o: unittest5.c
	gcc -c unittest5.c -g $(CFLAGS)

unittestresults: unittest1.o unittest2.o unittest3.o unittest4.o unittest5.o
	echo "Compiling unittestresults" >> unittestresults.out
	./unittest1 >> unittestresults.out
	./unittest2 >> unittestresults.out
	./unittest3 >> unittestresults.out
	./unittest4 >> unittestresults.out
	./unittest5 >> unittestresults.out
	gcov unittest1.c >> unittestresults.out
	gcov unittest2.c >> unittestresults.out
	gcov unittest3.c >> unittestresults.out
	gcov unittest4.c >> unittestresults.out
	gcov unittest5.c >> unittestresults.out
runtests: testDrawCard
	./testDrawCard &> unittestresult.out
	gcov dominion.c >> unittestresult.out
	cat dominion.c.gcov >> unittestresult.out


player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)

all: playdom player

clean:
	rm -f *.o playdom.exe playdom player player.exe  *.gcov *.gcda *.gcno *.so *.out testDrawCard testDrawCard.exe
